name: Convert
on:
  workflow_dispatch:
jobs:
  convert:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install "scikit-learn<=1.5.1"
          pip install torch
          pip install coremltools
          pip install safetensors

      - name: Convert
        run: |
          python safetensor_to_mlmodel.py mhgerman_print.safetensors -o mhgerman_print.mlmodel

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: MHD-mlmodel
          path: MHD.mlmodel
          retention-days: 5
